
services:
  app:
    image: php:8.3.16-fpm
    container_name: ecommerce_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  webserver:
    image: nginx:alpine
    container_name: nginx_server_ecommerce_api
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    networks:
      - laravel_network

  db:
    image: mysql:8.4.3
    container_name: mysql_db_ecommerce_api
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # ✅ Allow empty root password
    ports:
      - "3308:3306"
    networks:
      - laravel_network
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db       # Matches your MySQL service name
      PMA_PORT: 3306
    networks:
      - laravel_network
    depends_on:
      - db
      
networks:
  laravel_network:

volumes:
  dbdata:
